from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, DateTime, Float
from sqlalchemy.orm import relationship
from database import Base
import datetime

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    
    # Gamification & Cognitive
    xp = Column(Integer, default=0)
    level = Column(Integer, default=1)
    streak = Column(Integer, default=0)
    last_login = Column(DateTime, nullable=True)
    
    # Cognitive Engine
    current_burnout_score = Column(Float, default=0.0)
    average_fqi = Column(Float, default=75.0)
    relapse_risk = Column(Float, default=0.0)
    
    daily_goal_hours = Column(Float, default=2.0)
    weekly_goal_hours = Column(Float, default=10.0)
    
    preferences = relationship("UserPreferences", back_populates="user", uselist=False)
    tasks = relationship("Task", back_populates="user")
    sessions = relationship("StudySession", back_populates="user")
    habits = relationship("Habit", back_populates="user")

class UserPreferences(Base):
    __tablename__ = "user_preferences"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    study_hours = Column(Float, default=2.0)
    subjects = Column(String, default="")
    preferred_time = Column(String, default="evening")
    productivity_style = Column(String, default="pomodoro")
    
    study_plan = Column(String, nullable=True) # generated by Gemini
    
    user = relationship("User", back_populates="preferences")

class Task(Base):
    __tablename__ = "tasks"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    title = Column(String, index=True)
    subject_tag = Column(String, index=True, nullable=True)
    deadline = Column(DateTime, nullable=True)
    priority = Column(String, default="medium")
    status = Column(String, default="pending")
    
    estimated_minutes = Column(Integer, default=30)
    ai_priority_score = Column(Float, nullable=True)
    
    user = relationship("User", back_populates="tasks")

class StudySession(Base):
    __tablename__ = "study_sessions"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    subject = Column(String)
    duration_minutes = Column(Integer)
    start_time = Column(DateTime, default=datetime.datetime.utcnow)
    focus_score = Column(Integer, nullable=True) # 1-10
    focus_mode = Column(String, default="Deep Work")
    
    # Cognitive Engine
    fqi = Column(Integer, nullable=True) # 0-100 Focus Quality Index
    interruptions = Column(Integer, default=0)
    completed_successfully = Column(Boolean, default=True)
    
    user = relationship("User", back_populates="sessions")

class Habit(Base):
    __tablename__ = "habits"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    title = Column(String)
    streak = Column(Integer, default=0)
    last_completed = Column(DateTime, nullable=True)
    
    user = relationship("User", back_populates="habits")

class Addiction(Base):
    __tablename__ = "addictions"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    title = Column(String)
    reduction_goal = Column(String, nullable=True)
    current_streak = Column(Integer, default=0)
    last_relapse = Column(DateTime, nullable=True)
    
    user = relationship("User")
